### ISSUE TITLE
Module Incompatibility: Playlist Enhancer

### ISSUE THREAD

**Issue by akrigline** [CDeenen/Soundscape#11]
Another module which edits the behavior of dragging tracks around in the Playlist section. Playlist Enhancer lets you drag and drop sounds between playlists. This has the potential to be _super_ powerful when combined with Soundscape's ability to use a playlist all at once.

With both Soundscape and Playlist enhancer active, the dragging sounds between playlists ceases functioning, but the ability to drag sounds into the Soundscape tracks remains.

**Comment by CDeenen** [comment]
Thanks for pointing it out, I'll have a look at it

**Comment by CDeenen** [comment]
Due to the way Playlist Enhancer handles the dragging, it wasn't possible for me to find a workaround. Instead, I've created a PR with some modifications for Playlist Enhancer to make it compatible.
If they accept the changes, Soundscape will be compatible with Playlist Enhancer at the next update.

**Comment by CDeenen** [comment]
I believe this was fixed, and no longer really relevant since Playlist Enhancer appears to be abandoned.
