### ISSUE TITLE
Visual incompatibility with UI mods

### ISSUE THREAD

**Issue by Iankid** [CDeenen/Soundscape#12]
Of not are:
Dark UI for SFRPG,
and Ernie's Modern UI.
Guessing other UI mods as well.

Perhaps either a way for the mod to play better with these UI mods, or locking down UI changes from these mods

![soundmod-UI](https://user-images.githubusercontent.com/60759323/126018464-e76965af-ce90-47ce-965a-1ddcde1f3d6f.png)

**Comment by CDeenen** [comment]
Thanks for pointing it out, I'll see what I can do

**Comment by CDeenen** [comment]
I've given this some thought, and I don't think this is something that's easily fixable.
Especially now that Twilight UI has added support for Soundscape, I don't want to lock down UI changes. I don't know if it's possible to lock down UI changes on a module-to-module basis, so unless you or someone else has a solution, I'm going to keep it like it is.
I suggest that you request your favorite UI creator to add support for Soundscape.
