### ISSUE TITLE
[BUG] Module doesn't work in the Forge

### ISSUE THREAD

**Issue by CDeenen** [CDeenen/Soundscape#13]
Error when trying to play a sound: `MediaElementAudioSource outputs zeroes due to CORS access restrictions`

Possible solution: audio.crossOrigin="anonymous"
See [here](https://stackoverflow.com/questions/31083704/mediaelementaudiosource-outputs-zeroes-due-to-cors-access-restrictions/37806272) or [here](https://stackoverflow.com/questions/31308679/mediaelementaudiosource-outputs-zeros-due-to-cors-access-restrictions-local-mp3)

**Comment by CDeenen** [comment]
I tried the above mentioned solution, but that didn't seem to work.
I don't know if there's an easier way to code/debug for the Forge, because the way I've been doing it takes too long (I've had to push releases on github and manually install them in Foundry). For that reason I haven't investigated it that much.

**Comment by preslavb** [comment]
Hey, was just wondering if there's any motion on this bug? I quite like this module but since I've transitioned to using Forge I'm unable to use it and it's quite a shame.

**Comment by CDeenen** [comment]
Sorry, currently not. I've been quite busy the last few months, so I haven't had the time to look into this

**Comment by scomick** [comment]
Definitely going to follow this thread as well as I finally found something that could work for me but I'm also on the Forge :(

**Comment by Vzlainel** [comment]
Hello.  Its an excellent module idea but I also have encountered this bug.  I tried uninstalling this, reinstalling.  I also resorted to removing all audio add ons and then only trying this.  I reset the server between these module add/removals as well.  Unfortunately, all options resulted in a UI that opened but no volume on any audio track.  Note these tracks can be played using the base Forge sound UI.

During this period my players encountered strange issues with their character sheets (locked - unable to open). All of these issues disappeared when I uninstalled Soundscape.  The module works exceptionally well on my desktop but I really need to host the game on the cloud.  This means I will have to find another sound mixing option.

Please let me know if I can be of any assistance with debugging.

**Comment by CDeenen** [comment]
The module should now work using the Forge
