### ISSUE TITLE
[BUG] Shuffle Does Not Shuffle By Channel

### ISSUE THREAD

**Issue by WoodrumFamily24k** [CDeenen/Soundscape#15]
**Setup**
 - OS: Windows 10
 - Browser: Foundry App
 - Module version: V. 1.0.2
 - Foundry version: V. 0.8.8
 - Any other modules enabled: No

**Describe the bug**
When using multiple tracks from the same playlist or folder, rather than shuffling the tracks Soundscapes simply chooses the next track in the playlist/folder.

**Screenshots**
N/A

**Console Log**
Likely unrelated -
DevTools failed to load SourceMap: Could not load content for http://localhost:30000/modules/soundscape/lib/FileSaver.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Additional context**
This is a problem when trying to layer music 'stems' and/or ambiance pieces.

**Comment by CDeenen** [comment]
Thanks for posting this issue. I've found the bug and this will be fixed in the next update.
That console warning is indeed unrelated.
