### ISSUE TITLE
[BUG] Cannot get .isGM if game.users is nullish

### ISSUE THREAD

**Issue by arcanistzed** [CDeenen/Soundscape#17]
**Setup**
 - OS: Linux Mint
 - Browser: Chrome
 - Module version: 1.0.2
 - Foundry version: 0.8.9
 - Any other modules enabled: yes

**Describe the bug**
Cannot get property .isGM if game.users is nullish

**Screenshots**
![Screenshot from 2021-08-23 19-18-41](https://user-images.githubusercontent.com/82790112/130531472-fcd91686-9c16-437c-8fa4-a29c19cbd867.png)

**Console Log**
```
Uncaught (in promise) TypeError: Cannot read property 'isGM' of null
    at soundscape.js:14
```

**Comment by CDeenen** [comment]
Hey, this is a strange bug, since it tries to get `game.user.isGM`, so this means that game.user was null.
Would you mind disabling all other modules to see if it's a module incompatibility?

**Comment by arcanistzed** [comment]
I can't reproduce this issue anymore. Sorry and thanks :)
