### ISSUE TITLE
Fade Out Doesn't Seem to Work

### ISSUE THREAD

**Issue by illcom94** [CDeenen/Soundscape#19]
I'm attempting to have the thunder sound fade out so it's not so abrupt at the end when the rain sound in the background just cuts out. I've tried setting a fade out of 5 seconds, but it doesn't seem to do anything with this setup.

<img width="419" alt="Screen Shot 2021-09-18 at 12 16 19" src="https://user-images.githubusercontent.com/13877249/133906134-ef432e33-a8ab-47f8-8c4e-bbd644e25548.png">

**Comment by CDeenen** [comment]
Thanks for the bug report.
I found the issue, and will publish an update soon.

**Comment by illcom94** [comment]
Thanks!

**Comment by CDeenen** [comment]
This should be fixed
