### ISSUE TITLE
No sound plays

### ISSUE THREAD

**Issue by Cull3411** [CDeenen/Soundscape#20]
**Setup**
 - OS:Widows  10
 - Browser: Chrome
 - Module version: 1.0.0
 - Foundry version: 8.9
 - Any other modules enabled: Yes and then No

**Describe the bug**
No sounds activated by soundscape can be heard.
Oddly, the captioning works when speech is in the sound being played.
The playlist bar works fine otherwise.  All other sounds are heard normally.

**Screenshots**
None relevant that I know. 

**Console Log**
No errors.

**Additional context**
I just now ran it with no other modules and it does the same thing.  The mod looks very cool.  It looks like it would be better than Blitz's.

**Comment by CDeenen** [comment]
I'm not sure what you mean with 'captioning'.

Are you sure you're on module v1.0.0? The latest is v1.0.3, so if you are, please update and try again.
Also make sure that the Soundscape volume is not turned off (it's next to the other volume sliders in the playlist tab, under 'Global Volume Controls').
I assume you didn't mute, solo or turn down the volume, right?

In case that didn't fix it, could you please answer the following questions:
Did you try different files, and did you try both through the file picker and by selecting a playlist?
Is it not working for both the mixer and the soundboard?
Are you on the Forge, other hosting service, or self-hosted?
Is your server secured through SSL?

**Comment by Cull3411** [comment]
I uninstalled and reinstalled the module.

Same trouble on Firefox and Chrome.   Though Firefox doesn't give the captions.

With only Soundscape module running I'm seeing these warnings

One of these on each restart:
DevTools failed to load source map: Could not load content for https://assets.forge-vtt.com/bazaar/modules/soundscape/1.0.3/lib/FileSaver.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

100 - 400 of these on each restart:
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu


I'm not sure what you mean with 'captioning'.  

            See Screenshot. I never saw this before I loaded this module. 

            I like it.  I don't know how to control it. 

            That Caption you see is real time voice to text being generated from somewhere and is displayed on my screen as the voice in the audio clip speaks.


Are you sure you're on module v1.0.0? The latest is v1.0.3, so if you are, please update and try again.

                I'm on 1.0.3  (not sure that was a typo or miss-read on my part)

              

Also make sure that the Soundscape volume is not turned off (it's next to the other volume sliders in the playlist tab, under 'Global Volume Controls').
I assume you didn't mute, solo or turn down the volume, right?  

                See screenshot,  but no muting or anything.  

               VTT playlist can play the very same files Immoderately before and after I try Soundscape. 

               The VTT Playlist doesn't activate the captions.


In case that didn't fix it, could you please answer the following questions:
Did you try different files, and did you try both through the file picker and by selecting a playlist?

                Yes,  different files.  After messing with is a bit more I've found that they do play off of the Sound Importer tab.

 

Is it not working for both the mixer and the soundboard?

                   They do not play from the Mixer or the Soundboard.  I've tried several MP3s. 

                   I've tried to use all 4 different ways to choose a file on both the Mixer and the sound board.


Are you on the Forge, other hosting service, or self-hosted?

                  Forge


Is your server secured through SSL?

                   It's Forge.  Other than that I don't know.
![image](https://user-images.githubusercontent.com/77463883/134252596-f4d4d2d5-b720-4708-a2bd-a82544de7db8.png)

**Comment by CDeenen** [comment]
I'm afraid there's currently some issues when trying to use this module on the Forge, so that explains why the audio won't play. I'm completely baffled by the captioning, though. I haven't seen anything like that before.

Since there's already an issue open about Forge compatibility (https://github.com/CDeenen/Soundscape/issues/13), I'm going to close this one. If, after support for the Forge has been added, your issues persist, please let me know.
