### ISSUE TITLE
open Soundscape by macro

### ISSUE THREAD

**Issue by rogerioavsilva** [CDeenen/Soundscape#24]
Hi there, all good? do you know how can I open Soundscape (https://github.com/CDeenen/Soundscape) by macro?

**Comment by CDeenen** [comment]
There is no 'proper' way to do that, but the following works:
`document.getElementById('soundscapeOpen').click()`

I'll be adding a way to properly control most of the module through macros in the next update.

**Comment by rogerioavsilva** [comment]
Thank you so much, My idea is almost like a shortcut, it will work well.
