### ISSUE TITLE
[BUG] Drag and drop sounds from sound tab not working when soundscape is activated

### ISSUE THREAD

**Issue by Bekradan** [CDeenen/Soundscape#26]
**Setup**
 - OS: windows 10
 - Browser: chrome
 - Module version: 1.0.3
 - Foundry version: 9.242
 - Any other modules enabled: no

**Describe the bug**
With Soundscape activated, you cannot drag and drop sounds from the sound tab to the canvas.

Hopefully that's enough info, but let me know if you need more?

**Comment by CDeenen** [comment]
This should now be fixed
