### ISSUE TITLE
[BUG] Foundry Core drag and drop tracks into playlists not working

### ISSUE THREAD

**Issue by findlaycopley** [CDeenen/Soundscape#27]
When Soundscapes is active I am unable to drag and drop songs between playlists, which is now part of foundry core.

I tried this on a fresh world with no modules and drag and drop worked then stopped as soon as I load Soundscape.

I know there used to be a work around with Playlist Enhancer for this issue too (PE has subsequently removed this feature as it is now native to Foundry)

Foundry Virtual Tabletop: Version 9, 9.269
Soundscape version 1.0.3

**Comment by CDeenen** [comment]
Thanks for your bug report.
Unfortunately, due to time constraints, this module is currently not in active development.
If it ever gets an update, I'll try to fix this and update this issue, but I can't tell you when (or if) that will happen.

**Comment by CDeenen** [comment]
I just released an update and this should be fixed
