### ISSUE TITLE
[BUG]Cross-origin audio sources do not play

### ISSUE THREAD

**Issue by rikmarais** [CDeenen/Soundscape#28]
**Setup**
 - OS: Windows / Hosting: The Forge
 - Browser: Foundry App / Chrome / Firefox
 - Module version: 1.0.3
 - Foundry version: Version 9 - Build 269
 - Any other modules enabled: Yes: The Forge

**Describe the bug**
Cross origin audio sources do not play. In this example, the audio source is hosted on the internet on my Assets Library with The Forge, but I suspect this will affect hosting assets on S3 or elsewhere as well.

This also affects games run on The Forge, where assets are generally in the Assets Library.

**Screenshots**
![image](https://user-images.githubusercontent.com/34374883/182041017-64d8902d-88f7-4b78-8cbf-d9183c5804ea.png)

**Console Log**
```text
MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://assets.forge-vtt.com/60f7456e32c9b51777fd4f03/sfx/Ghost/Ghost%20Attack%20(Screech).wav
```

**Additional context**
Setting `this.audioElement.crossOrigin = "";` in the dev tools for `channel.js` `setSource` function before `createMediaElementSource` is called sets a cross origin behaviour and allows the sound to play.

**Comment by rikmarais** [comment]
Duplicate of #13

**Comment by CDeenen** [comment]
The module should now work using the Forge
