### ISSUE TITLE
Add support for Material Deck and Material Keys

### ISSUE THREAD

**Issue by CDeenen** [CDeenen/Soundscape#3]

**Comment by ghost91-** [comment]
I have another suggestion that goes into a similar direction: MIDI controller support. But I guess this would be much more complicated than simply integrating a module like Material Keys. But it would be great, nonetheless!

**Comment by CDeenen** [comment]
That's definitely something I want to add. I'm not sure yet whether it'd be part of Soundscape, or whether it'd be a dedicated MIDI module that can control Soundscape but also do other stuff.
I'd really love to be able to control Soundscape using something like a Behringer X-Touch, and I have actually done some experimenting with motorized faders: https://youtu.be/I8maolIlqxM
I don't know when I have the time to properly implement it, though.

**Comment by CDeenen** [comment]
Support for Material Deck and Material Keys (and other modules or macros) has been added to v1.0.3
