### ISSUE TITLE
Randomize playback of sound effects

### ISSUE THREAD

**Issue by trdischat** [CDeenen/Soundscape#5]
Your module already provides the ability to randomize sounds by playing a given slot from a selection of audio samples in a playlist or folder. That is great, but to create soundscapes that are less obviously repetitive it would be great to be able to configure individual sound effect slots to play at random intervals with random volume changes. I described this idea in a bit more detail [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/4718) when I suggested it for incorporation into the Foundry core. I also suggested including this in the SoundBoard module [here](https://github.com/BlitzKraig/fvtt-SoundBoard/issues/48). A bonus idea that builds on what is already in your module would be random audio effects like speed, tuning, or reverb, but the random playback intervals are the real key.

**Comment by CDeenen** [comment]
I like that idea, I'll look into implementing it, thanks!

**Comment by trdischat** [comment]
Congrats in winning the Foundry's Choice Award!!

Very well deserved.

**Comment by CDeenen** [comment]
Both random delay and random volume has been added to v1.0.3
