### ISSUE TITLE
Cannont Set Soundscape Name [BUG]

### ISSUE THREAD

**Issue by LEronsn** [CDeenen/Soundscape#6]
When choosing a Name for the Soundscape Board, an error (jquery) occur: 

mixerApp.js:260 Uncaught TypeError: this.mixer.setSoundscapeName is not a function
    at HTMLInputElement.<anonymous> (mixerApp.js:260)
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.v.handle (jquery.min.js:2)
(anonymous) @ mixerApp.js:260
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by CDeenen** [comment]
Thanks for the bug report.
It should be fixed in the latest version (v1.0.2)

**Comment by LEronsn** [comment]
Thx! Keep up the good work!
