### ISSUE TITLE
Add option to assign a player to take control of the mixer

### ISSUE THREAD

**Issue by CDeenen** [CDeenen/Soundscape#8]

**Comment by MrManlyPrincess** [comment]
I noticed a setting "targetPlayer" that seems related to this.
Is this a feature that you're working on or have partially implemented?

**Comment by CDeenen** [comment]
I was working on it, but didn't finish it. I forgot to remove the setting before pushing the update :)

**Comment by CDeenen** [comment]
This has been added in the latest update
