### ISSUE TITLE
Improved Loop - "Apply timings after the first loop"

### ISSUE THREAD

**Issue by apoapostolov** [CDeenen/Soundscape#9]
I really like that Soundscape allows trimmed timing of playlist sounds but would love to see this feature expanded with a new option for "post-start loop" which makes sounds start at the beginning but when they reach the end timing, they fade into the start timing for an endless loop. 

A typical fantasy score music has parts that are not fit for a loop during combat. They start with a mellow buildup, then hit the loud and dynamic battle theme, then often have a slow downhill end. Due to this, looping that sound would be constantly entering mellow buildups for half a minute of battle theme, so on and so forth.

Thanks to Soundscape's ability to have timings inside the song this can be solved very elegantly. Just one checkbox that says "Apply timing after the first loop" so that songs start from the start only once, and then fade through in the loop. 

Example: A 00:60.000 combat melody has a buildup from 00:00.000 to 00:30.00, then blasts epic battle from 00:30.000 until 00:54.000. it also has a 00:06.000 (12000ms) fade. The DM turns on "Apply timing after the first loop", then sets start timing to 00:34.00 and the end timing at 00:54.000. The song starts from 00:00.000 as normal. When the song gets close to 00:54.000 - 00:06.000, it starts to fade into the same song that starts from 00:35.000. This means that the slow ballad buildup will only be heard once, and the rest will be endless combat epicness until the theme is stopped.

**Comment by CDeenen** [comment]
This has been added to v1.0.3
